server:
  port: 8080
spring:
  datasource:
#    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:codetracker}
    url: jdbc:postgresql://localhost:5432/code_tracker
#    username: ${DB_USER:postgres}
    username: postgres
#    password: ${DB_PASS:postgres}
    password: password14..
  jpa:
    hibernate:
      ddl-auto: update   # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  logging:
    level:
      org.springframework.transaction: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

#flyway:
#  enabled: true
#  locations: classpath:db/migration

app:
  jwt:
    secret: change-this-secret-to-a-strong-one
    access-validity-seconds: 900 # 15m
    refresh-validity-seconds: 604800 # 7d

cors:
  allowed-origins:
    - http://localhost:5173/

logging:
  level:
    root: INFO